### ISSUE TITLE
Add support for excluding binary files

### ISSUE THREAD

**Issue by guyzyl** [onebadidea/swiftquit#10]
Currently, the exclude screen only allows to select MacOS applications.
The problem is that there are some binary software that are not MacOS apps but have a window open up.
It would be great to enable excluding those.

Python is an example for such thing (and the binary I ran into issues with).
A Python script can open up a GUI window, but the Python binary can't be excluded in SwiftQuit.

**Comment by onebadidea** [comment]
I enabled the exclusion of all files, but have not tested.

**Comment by guyzyl** [comment]
@onebadidea thanks!
