### ISSUE TITLE
Extend the approach a bit - adding a list of applicatons that must be closed

### ISSUE THREAD

**Issue by YuriiKravtsov** [onebadidea/swiftquit#12]
Although I like the utility that really helps to close unnecessary, "sticking in the void" applications without windows, I've faced multiple times a case when the application was closed in the middle of its working flow due to the fact that itdidn't have any window at that moment. 
This mostly relates to various utilities, some times it happened during installation of a new app, etc. 
In this case, I have to add this application as an exception and it works fine, but I would like to propose to consider another approach for this utility. Instead of choosing applications that shouldn't be closed, let's collect a list of applications that should be closed and ignore the others. 
I've found out that I need this functionality mostly for so-called MDI applications like MS Offices ones. To be honest, it's pretty small range as for me, and I guess, for any regular user. At least this approach will help to avoid the cases I mentioned earlier when just downloaded app/utility disappeared without any warnings and the user hardly understands what was a reason. 
Overall, the great utility!
Thank you!

**Comment by onebadidea** [comment]
@ YuriiKravtsov
Thanks @logwet for implementing this feature and other enhancements.

**Comment by YuriiKravtsov** [comment]
@logwet @onebadidea Thank you very much!!
