### ISSUE TITLE
Use GitHub Releases for easy Homebrew-ification

### ISSUE THREAD

**Issue by logwet** [onebadidea/swiftquit#17]
I would like to make a homebrew cask for Swift Quit. This would be easier if versioning and releases were handled through Github Releases and tagged appropriately (through git) with the release version.

**Comment by onebadidea** [comment]
@logwet Ok that sounds great, I've enabled releases and created one for v1.3.

**Comment by logwet** [comment]
Made a PR Homebrew/homebrew-cask#142000
