### ISSUE TITLE
Error: Swift Quit.app can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by niteshmanav** [onebadidea/swiftquit#20]
Getting this error: " Swift Quit .app " can't be opened because Apple cannot check it for malicious software . This software needs to be updated . Contact the developer for more information .
        
Screenshot: https://a.cl.ly/llu744j7

Can you please resolve this issue?

Thank you.

**Comment by onebadidea** [comment]
You need to go to System Preferences => Security => General and allow it to open there.  Here is a link to a video showing how to do it on Monterey OS.  It will be slightly different if you are running the newest version of Mac OS.  https://www.youtube.com/watch?v=kn3rRYsipG8

**Comment by ris58h** [comment]
@niteshmanav I believe the reason you getting this message is because the app is ad-hoc signed (@onebadidea am I right about it?).
The workaround is to right-click the app and click `Open`, a pop-up will appear, click `Open` again.

**Comment by onebadidea** [comment]
@niteshmanav Yes the app has not been notarized by apple.  Working on this.  Thanks for sharing the workaround.
