### ISSUE TITLE
Wrong checksum for brew cask

### ISSUE THREAD

**Issue by leahachase** [onebadidea/swiftquit#24]
Hi there,

The brew cask for this tool appears to be broken, it's expecting the wrong SHA-256 hash. Below is the output of `brew install ‑‑cask swift‑quit`:

```
Error: SHA256 mismatch
Expected: d8ea2cd7fe36fd83253e4654c029ea17239a80ed34ca2faab67b65cea0383594
  Actual: a4e467cb13a14dcff3ca4047179ba3b16119f458cd6ae2467810f3f5b9c74efb
    File: /Users/leahchase/Library/Caches/Homebrew/downloads/7f97dc53a60dc609f2b7e28ffb1f255cfe3feaa185d4adf1033092ac02465661--Swift.Quit.zip
To retry an incomplete download, remove the file above.
``` 

I've tried removing the cached file, but I get the same error. I've also double-checked by downloading the .zip directly from here and running `shasum ‑a 256`, but it has the same hash as when downloaded by brew (i.e., `a4e467c`)

I've tried using `brew bump‑cask‑pr` a few times but I can't quite get the hang of it, can someone more experienced with homebrew put in the pull request for me?

@logwet, @razvanazamfirei?

**Comment by razvanazamfirei** [comment]
@leahachase Hi! Thank you for flagging this. The .zip was updated after the cask was bumped which caused the mismatch. I opened a PR in the homebrew-cask repo which should fix the issue!
