### ISSUE TITLE
Delay before quiting

### ISSUE THREAD

**Issue by realAbitbol** [onebadidea/swiftquit#3]
Hey, thanks for the great app :)
I'd like to suggest an enhancement : Add a delay setting before closing apps with no window.

It would really be useful for apps like Excel because when I run it and select a file using it it then closes the main window for a second while loading the file and it gets insta-quit by swiftquit before being able to display the file.

**Comment by marjue12255** [comment]
Hello
Yes this would be a nice feature. MS Teams is a candidate for that. It quits after showing a splash screen.
Or maybe you could implement the opportunity to have a include list instead of the exclude list for the apps.

Greetings

**Comment by michaelmior** [comment]
Same thing happens with Preview.app if you start it directly without opening a particular file.

**Comment by dacriku** [comment]
+1
Would be very helpful for all Office365 apps. Currently they do not work with swift quit as described by @realAbitbol

**Comment by incanus** [comment]
Another vote here. A few Apple apps (Numbers, Pages, Script Editor) start with an "open or create document" pane and if you click any of its actions, the pane disappears before the window appears, except that it doesn't since the app quits instead.

**Comment by phldgmn** [comment]
Could you maybe extend this further or make it configurable? I have the issue that Word starts up fine, but if I open a larger document that takes maybe 3 seconds to open, Word closes nearly instantly when the Window finally opens. Thanks!
