### ISSUE TITLE
Open swiftquit without opening the settings window

### ISSUE THREAD

**Issue by samcarter** [onebadidea/swiftquit#30]
First of all, thanks a lot for this app! A very useful idea with a lot of potential! 

Your app is a very useful tool, one configures it once and then can basically forget about it because it simply does its job in the background (with the rare exception if having to add/remove an app every once in a while). To this extend, I'm using your app with the menu bar icon hidden. Currently the only time I get reminded about your app is when I restart my computer and have to click the settings dialogue closed.

Is there any way to open this app automatically on login without the settings window opening automatically? As far as I can see, the settings window is not automatically shown when the menu bar icon is visible, but if the menu bar icon is disabled, the settings window will automatically open.

I presume that's to give users an option to access the settings? Some other applications solve this by not opening the settings window when they are first opened and if one needs to access the settings, one can launch them again which will open the settings.  Some examples which can be used in this way are https://github.com/objective-see/LuLu or https://github.com/rxhanson/Rectangle I don't know if such a behaviour would be possible with swiftquit, but it might be a nice feature for users like me.

I'm using Swift Quit v1.5 on macOS 13.3.1

**Comment by Erik262** [comment]
Came here to report that "issue" as well....

**Comment by samcarter** [comment]
I tried the PR https://github.com/onebadidea/swiftquit/pull/32 by @mshll and it works fabulously. 

Please close this feature request when the PR gets merged
