### ISSUE TITLE
Command + Space for Spotlight does not work

### ISSUE THREAD

**Issue by marjue12255** [onebadidea/swiftquit#4]
Hello

Today I’ve installed your little tool an I like it a lot because I switched from Win to Mac a year ago and don’t like that apps stays open when the last window was closed.

But there is a problem with spotlight. The keystroke command+space does not work when the tool is running. The little search-window does not show up.
I‘m using a MB-Pro 16" 2021 M1Pro with Ventura 13.1

An additional note:
After starting SwiftQuit command+space is working one time. It seams SwiftQuit is killing a process which is needed by Spotlight search after it's last window (the input field" is closed.

By the way:
It is not possible to send you an email.

```
-Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------
193203F581     1142 Tue Dec 20 16:00:31  my_own@email.eu
          (connect to swiftquit.com[147.182.230.194]:25: Connection timed out)
                                         info@swiftquit.com
```

Hope you can fix this or tell me a workaround

**Comment by marjue12255** [comment]
Found the solution:
Added "/System/Library/CoreServices/Spotlight.app" to the exclude list.

**Comment by onebadidea** [comment]
Got it.  I've added both spotlight and finder to the default exclusion list for now.
